name: insta_clone_clean_arch
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  flutter_bloc: ^8.1.2

  equatable: ^2.0.5

  # firebase
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14

  # service locator
  get_it: ^7.2.0

  flutter_svg: ^1.1.6
  image_picker: ^0.8.6+3

  # localization
  intl: ^0.17.0
  uuid: ^3.0.7
  cached_network_image: ^3.2.3

  # show toast
  fluttertoast: ^8.2.1
  modal_bottom_sheet: ^2.1.2
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
